submit block_mpi 2
submit loop_mpi 2
submit pipe_mpi 2
submit omp_mpi 2
submit sse_mpi 2
submit avx_mpi 2
submit block_mpi 4
submit loop_mpi 4
submit pipe_mpi 4
submit omp_mpi 4
submit sse_mpi 4
submit avx_mpi 4
submit block_mpi 8
submit loop_mpi 8
submit pipe_mpi 8
submit omp_mpi 8
submit sse_mpi 8
submit avx_mpi 8
